In [1]:
!pip install gymnasium

  Could not fetch URL https://pypi.python.org/simple/gymnasium/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749) - skipping


  Could not find a version that satisfies the requirement gymnasium (from versions: )
No matching distribution found for gymnasium


In [2]:
import gymnasium as gym
from gymnasium.spaces import Discrete,MultiDiscrete,Box,MultiBinary
import numpy as np

In [3]:
MultiDiscrete([3,3]).sample()

array([2, 0], dtype=int64)

In [7]:
Box(low=-1.0, high = 2.0,shape=(1,2),dtype=np.float32).sample()

array([[-0.3249067 , -0.17734562]], dtype=float32)

In [27]:
Box(low=np.array([-1.0,-2.0]), high = np.array([2.0,3.0]),shape=(2,),dtype=np.float32).sample()

array([ 1.6994888, -1.5098727], dtype=float32)